-- Vistas
CREATE MATERIALIZED VIEW MV_INVENTARIO_CRITICO
REFRESH COMPLETE START WITH SYSDATE NEXT SYSDATE + 1
AS
SELECT 
    s.NOMBRE_SUCURSAL,
    p.NOMBRE_PRODUCTO,
    i.CANTIDAD_STOCK,
    i.CANTIDAD_MINIMA,
    CASE 
        WHEN i.CANTIDAD_STOCK <= i.CANTIDAD_MINIMA THEN 'CRÍTICO'
        WHEN i.CANTIDAD_STOCK <= (i.CANTIDAD_MINIMA * 1.5) THEN 'BAJO'
        ELSE 'NORMAL'
    END AS ESTADO_STOCK,
    pr.NOMBRE_PROVEEDOR
FROM FIDE_INVENTARIOS_TB i
JOIN FIDE_PRODUCTOS_TB p ON i.FIDE_INVENTARIOS_ID_PRODUCTO_FK = p.FIDE_PRODUCTOS_ID_PRODUCTO_PK
JOIN FIDE_SUCURSALES_TB s ON i.FIDE_INVENTARIOS_ID_SUCURSAL_FK = s.FIDE_SUCURSALES_ID_SUCURSAL_PK
JOIN FIDE_PROVEEDORES_TB pr ON p.FIDE_PRODUCTOS_ID_PROVEEDOR_FK = pr.FIDE_PROVEEDORES_ID_PROVEEDOR_PK
WHERE i.CANTIDAD_STOCK <= i.CANTIDAD_MINIMA * 1.5
AND i.FIDE_INVENTARIOS_ID_ESTADO_FK = 1;

CREATE OR REPLACE VIEW V_VENTAS_SUCURSAL_MES AS
SELECT 
    s.NOMBRE_SUCURSAL,
    EXTRACT(YEAR FROM f.FECHA_FACTURA) AS ANIO,
    EXTRACT(MONTH FROM f.FECHA_FACTURA) AS MES,
    COUNT(*) AS TOTAL_VENTAS,
    SUM(f.TOTAL) AS INGRESOS_TOTALES,
    AVG(f.TOTAL) AS PROMEDIO_VENTA
FROM FIDE_FACTURAS_TB f
JOIN FIDE_SUCURSALES_TB s ON f.FIDE_FACTURAS_ID_SUCURSAL_FK = s.FIDE_SUCURSALES_ID_SUCURSAL_PK
WHERE f.FIDE_FACTURAS_ID_ESTADO_FK = 1
GROUP BY s.NOMBRE_SUCURSAL, EXTRACT(YEAR FROM f.FECHA_FACTURA), EXTRACT(MONTH FROM f.FECHA_FACTURA);

CREATE OR REPLACE VIEW V_CLIENTES_LEALTAD AS
SELECT 
    u.FIDE_USUARIOS_ID_USUARIO_PK AS ID_CLIENTE,
    u.CEDULA,
    u.NOMBRE || ' ' || u.APELLIDO_PATERNO || ' ' || COALESCE(u.APELLIDO_MATERNO, '') AS NOMBRE_COMPLETO,
    u.PUNTOS_LEALTAD,
    c.CORREO,
    t.TELEFONO,
    (SELECT COUNT(*) FROM FIDE_FACTURAS_TB f WHERE f.FIDE_FACTURAS_ID_CLIENTE_FK = u.FIDE_USUARIOS_ID_USUARIO_PK) AS TOTAL_COMPRAS,
    (SELECT SUM(TOTAL) FROM FIDE_FACTURAS_TB f WHERE f.FIDE_FACTURAS_ID_CLIENTE_FK = u.FIDE_USUARIOS_ID_USUARIO_PK) AS MONTO_TOTAL_COMPRAS
FROM FIDE_USUARIOS_TB u
LEFT JOIN FIDE_CORREOS_TB c ON u.FIDE_USUARIOS_ID_CORREO_FK = c.FIDE_CORREOS_ID_CORREO_PK
LEFT JOIN FIDE_TELEFONOS_TB t ON u.FIDE_USUARIOS_ID_TELEFONO_FK = t.FIDE_TELEFONOS_ID_TELEFONO_PK
WHERE u.TIPO_USUARIO = 'CLIENTE'
AND u.FIDE_USUARIOS_ID_ESTADO_FK = 1;

CREATE MATERIALIZED VIEW MV_PRODUCTOS_VENCIMIENTO
REFRESH COMPLETE START WITH SYSDATE NEXT SYSDATE + 1
AS
SELECT 
    p.NOMBRE_PRODUCTO,
    p.FECHA_VENCIMIENTO,
    i.CANTIDAD_STOCK,
    s.NOMBRE_SUCURSAL,
    cat.NOMBRE_CATEGORIA,
    CASE 
        WHEN p.FECHA_VENCIMIENTO <= SYSDATE THEN 'VENCIDO'
        WHEN p.FECHA_VENCIMIENTO <= SYSDATE + 30 THEN 'PRÓXIMO A VENCER'
        ELSE 'VIGENTE'
    END AS ESTADO_VENCIMIENTO
FROM FIDE_PRODUCTOS_TB p
JOIN FIDE_INVENTARIOS_TB i ON p.FIDE_PRODUCTOS_ID_PRODUCTO_PK = i.FIDE_INVENTARIOS_ID_PRODUCTO_FK
JOIN FIDE_SUCURSALES_TB s ON i.FIDE_INVENTARIOS_ID_SUCURSAL_FK = s.FIDE_SUCURSALES_ID_SUCURSAL_PK
JOIN FIDE_CATEGORIAS_TB cat ON p.FIDE_PRODUCTOS_ID_CATEGORIA_FK = cat.FIDE_CATEGORIAS_ID_CATEGORIA_PK
WHERE p.FECHA_VENCIMIENTO <= SYSDATE + 60
AND p.FIDE_PRODUCTOS_ID_ESTADO_FK = 1;

CREATE OR REPLACE VIEW V_EMPLEADOS_SUCURSAL AS
SELECT 
    u.FIDE_USUARIOS_ID_USUARIO_PK AS ID_EMPLEADO,
    u.CEDULA,
    u.NOMBRE || ' ' || u.APELLIDO_PATERNO || ' ' || COALESCE(u.APELLIDO_MATERNO, '') AS NOMBRE_COMPLETO,
    p.NOMBRE_PUESTO,
    u.SALARIO,
    s.NOMBRE_SUCURSAL,
    u.FECHA_CONTRATACION,
    c.CORREO,
    t.TELEFONO,
    (SELECT COUNT(*) FROM FIDE_ASISTENCIA_TB a 
     WHERE a.FIDE_ASISTENCIA_ID_EMPLEADO_FK = u.FIDE_USUARIOS_ID_USUARIO_PK 
     AND EXTRACT(MONTH FROM a.FECHA_ASISTENCIA) = EXTRACT(MONTH FROM SYSDATE)) AS DIAS_TRABAJADOS_MES
FROM FIDE_USUARIOS_TB u
JOIN FIDE_PUESTOS_TB p ON u.FIDE_USUARIOS_ID_PUESTO_FK = p.FIDE_PUESTOS_ID_PUESTO_PK
JOIN FIDE_SUCURSALES_TB s ON u.FIDE_USUARIOS_ID_SUCURSAL_FK = s.FIDE_SUCURSALES_ID_SUCURSAL_PK
LEFT JOIN FIDE_CORREOS_TB c ON u.FIDE_USUARIOS_ID_CORREO_FK = c.FIDE_CORREOS_ID_CORREO_PK
LEFT JOIN FIDE_TELEFONOS_TB t ON u.FIDE_USUARIOS_ID_TELEFONO_FK = t.FIDE_TELEFONOS_ID_TELEFONO_PK
WHERE u.TIPO_USUARIO = 'EMPLEADO'
AND u.FIDE_USUARIOS_ID_ESTADO_FK = 1;

CREATE OR REPLACE VIEW V_PROMOCIONES_ACTIVAS AS
SELECT 
    prom.NOMBRE_PROMOCION,
    prom.DESCRIPCION,
    prom.FECHA_INICIO,
    prom.FECHA_FIN,
    d.NOMBRE_DESCUENTO,
    d.PORCENTAJE AS PORCENTAJE_DESCUENTO,
    p.NOMBRE_PRODUCTO,
    CASE 
        WHEN SYSDATE BETWEEN prom.FECHA_INICIO AND prom.FECHA_FIN THEN 'ACTIVA'
        ELSE 'INACTIVA'
    END AS ESTADO_PROMOCION,
    (SELECT COUNT(*) FROM FIDE_CLIENTES_DESCUENTO_TB cd 
     WHERE cd.FIDE_CLIENTES_DESCUENTO_ID_PROMOCION_FK = prom.FIDE_PROMOCIONES_ID_PROMOCION_PK) AS CLIENTES_BENEFICIADOS
FROM FIDE_PROMOCIONES_TB prom
LEFT JOIN FIDE_DESCUENTOS_TB d ON prom.FIDE_PROMOCIONES_ID_DESCUENTO_FK = d.FIDE_DESCUENTOS_ID_DESCUENTO_PK
LEFT JOIN FIDE_PRODUCTOS_TB p ON prom.FIDE_PROMOCIONES_ID_PRODUCTO_FK = p.FIDE_PRODUCTOS_ID_PRODUCTO_PK
WHERE SYSDATE BETWEEN prom.FECHA_INICIO AND prom.FECHA_FIN
AND prom.FIDE_PROMOCIONES_ID_ESTADO_FK = 1;

CREATE OR REPLACE VIEW V_COMPRAS_PENDIENTES AS
SELECT 
    c.NUMERO_ORDEN,
    c.FECHA_ORDEN,
    c.FECHA_ESTIMADA_ENTREGA,
    c.TOTAL_COMPRA,
    c.ESTADO_COMPRA,
    p.NOMBRE_PROVEEDOR,
    p.CONTACTO AS CONTACTO_PROVEEDOR,
    s.NOMBRE_SUCURSAL,
    u.NOMBRE || ' ' || u.APELLIDO_PATERNO AS EMPLEADO_RESPONSABLE,
    (SELECT COUNT(*) FROM FIDE_DETALLES_COMPRA_TB dc 
     WHERE dc.FIDE_DETALLES_COMPRA_ID_COMPRA_FK = c.FIDE_COMPRAS_ID_COMPRA_PK) AS TOTAL_PRODUCTOS
FROM FIDE_COMPRAS_TB c
JOIN FIDE_PROVEEDORES_TB p ON c.FIDE_COMPRAS_ID_PROVEEDOR_FK = p.FIDE_PROVEEDORES_ID_PROVEEDOR_PK
JOIN FIDE_SUCURSALES_TB s ON c.FIDE_COMPRAS_ID_SUCURSAL_FK = s.FIDE_SUCURSALES_ID_SUCURSAL_PK
JOIN FIDE_USUARIOS_TB u ON c.FIDE_COMPRAS_ID_EMPLEADO_FK = u.FIDE_USUARIOS_ID_USUARIO_PK
WHERE c.ESTADO_COMPRA IN ('PENDIENTE', 'EN_TRANSITO')
AND c.FIDE_COMPRAS_ID_ESTADO_FK = 1;

CREATE MATERIALIZED VIEW MV_PLANILLAS_EMPLEADOS
REFRESH COMPLETE START WITH SYSDATE NEXT SYSDATE + 1
AS
SELECT 
    pl.MES,
    pl.ANIO,
    u.CEDULA,
    u.NOMBRE || ' ' || u.APELLIDO_PATERNO || ' ' || COALESCE(u.APELLIDO_MATERNO, '') AS NOMBRE_EMPLEADO,
    p.NOMBRE_PUESTO,
    s.NOMBRE_SUCURSAL,
    pl.SALARIO_BRUTO,
    pl.DEDUCCIONES,
    pl.SALARIO_NETO,
    ROUND((pl.DEDUCCIONES / pl.SALARIO_BRUTO) * 100, 2) AS PORCENTAJE_DEDUCCION
FROM FIDE_PLANILLAS_TB pl
JOIN FIDE_USUARIOS_TB u ON pl.FIDE_PLANILLAS_ID_EMPLEADO_FK = u.FIDE_USUARIOS_ID_USUARIO_PK
JOIN FIDE_PUESTOS_TB p ON u.FIDE_USUARIOS_ID_PUESTO_FK = p.FIDE_PUESTOS_ID_PUESTO_PK
JOIN FIDE_SUCURSALES_TB s ON pl.FIDE_PLANILLAS_ID_SUCURSAL_FK = s.FIDE_SUCURSALES_ID_SUCURSAL_PK
WHERE pl.FIDE_PLANILLAS_ID_ESTADO_FK = 1
ORDER BY pl.ANIO DESC, pl.MES DESC;

CREATE OR REPLACE VIEW V_TOP_PRODUCTOS_VENDIDOS AS
SELECT 
    p.NOMBRE_PRODUCTO,
    cat.NOMBRE_CATEGORIA,
    SUM(df.CANTIDAD) AS TOTAL_VENDIDO,
    SUM(df.SUBTOTAL) AS INGRESOS_TOTALES,
    COUNT(DISTINCT df.FIDE_DETALLES_FACTURA_ID_FACTURA_FK) AS TOTAL_VENTAS,
    ROUND(AVG(df.PRECIO_UNITARIO), 2) AS PRECIO_PROMEDIO
FROM FIDE_DETALLES_FACTURA_TB df
JOIN FIDE_PRODUCTOS_TB p ON df.FIDE_DETALLES_FACTURA_ID_PRODUCTO_FK = p.FIDE_PRODUCTOS_ID_PRODUCTO_PK
JOIN FIDE_CATEGORIAS_TB cat ON p.FIDE_PRODUCTOS_ID_CATEGORIA_FK = cat.FIDE_CATEGORIAS_ID_CATEGORIA_PK
JOIN FIDE_FACTURAS_TB f ON df.FIDE_DETALLES_FACTURA_ID_FACTURA_FK = f.FIDE_FACTURAS_ID_FACTURA_PK
WHERE df.FIDE_DETALLES_FACTURA_ID_ESTADO_FK = 1
AND f.FIDE_FACTURAS_ID_ESTADO_FK = 1
GROUP BY p.NOMBRE_PRODUCTO, cat.NOMBRE_CATEGORIA
ORDER BY TOTAL_VENDIDO DESC;

CREATE OR REPLACE VIEW V_PROVEEDORES_HISTORIAL AS
SELECT 
    p.FIDE_PROVEEDORES_ID_PROVEEDOR_PK AS ID_PROVEEDOR,
    p.NOMBRE_PROVEEDOR,
    p.CONTACTO,
    c.CORREO,
    t.TELEFONO,
    COUNT(comp.FIDE_COMPRAS_ID_COMPRA_PK) AS TOTAL_COMPRAS,
    SUM(comp.TOTAL_COMPRA) AS MONTO_TOTAL_COMPRAS,
    AVG(comp.TOTAL_COMPRA) AS PROMEDIO_COMPRA,
    MAX(comp.FECHA_ORDEN) AS ULTIMA_COMPRA,
    (SELECT COUNT(*) FROM FIDE_CONTRATOS_PROVEEDORES_TB cp 
     WHERE cp.FIDE_CONTRATOS_PROVEEDORES_ID_PROVEEDOR_FK = p.FIDE_PROVEEDORES_ID_PROVEEDOR_PK 
     AND cp.FIDE_CONTRATOS_PROVEEDORES_ID_ESTADO_FK = 1) AS CONTRATOS_ACTIVOS
FROM FIDE_PROVEEDORES_TB p
LEFT JOIN FIDE_COMPRAS_TB comp ON p.FIDE_PROVEEDORES_ID_PROVEEDOR_PK = comp.FIDE_COMPRAS_ID_PROVEEDOR_FK
LEFT JOIN FIDE_CORREOS_TB c ON p.FIDE_PROVEEDORES_ID_CORREO_FK = c.FIDE_CORREOS_ID_CORREO_PK
LEFT JOIN FIDE_TELEFONOS_TB t ON p.FIDE_PROVEEDORES_ID_TELEFONO_FK = t.FIDE_TELEFONOS_ID_TELEFONO_PK
WHERE p.FIDE_PROVEEDORES_ID_ESTADO_FK = 1
GROUP BY p.FIDE_PROVEEDORES_ID_PROVEEDOR_PK, p.NOMBRE_PROVEEDOR, p.CONTACTO, c.CORREO, t.TELEFONO
ORDER BY MONTO_TOTAL_COMPRAS DESC;
