-- Tabla de Estados
CREATE TABLE FIDE_ESTADOS_TB (
    FIDE_ESTADOS_ID_ESTADO_PK NUMBER,
    NOMBRE_ESTADO             VARCHAR2(50) NOT NULL,
    CONSTRAINT FIDE_ESTADOS_ID_ESTADO_PK PRIMARY KEY (FIDE_ESTADOS_ID_ESTADO_PK)
);

CREATE INDEX FIDE_ESTADOS_NOMBRE_IDX ON FIDE_ESTADOS_TB (NOMBRE_ESTADO);

-- Tabla de Provincias
CREATE TABLE FIDE_PROVINCIAS_TB (
    FIDE_PROVINCIAS_ID_PROVINCIA_PK NUMBER,
    NOMBRE_PROVINCIA                VARCHAR2(100) NOT NULL,
    FIDE_PROVINCIAS_ID_ESTADO_FK    NUMBER,
    CONSTRAINT FIDE_PROVINCIAS_ID_PROVINCIA_PK PRIMARY KEY (FIDE_PROVINCIAS_ID_PROVINCIA_PK),
    CONSTRAINT FIDE_PROVINCIAS_ID_ESTADO_FK FOREIGN KEY (FIDE_PROVINCIAS_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK)
);

CREATE INDEX FIDE_PROVINCIAS_NOMBRE_IDX ON FIDE_PROVINCIAS_TB (NOMBRE_PROVINCIA);
CREATE INDEX FIDE_PROVINCIAS_ESTADO_IDX ON FIDE_PROVINCIAS_TB (FIDE_PROVINCIAS_ID_ESTADO_FK);

-- Tabla de Cantones
CREATE TABLE FIDE_CANTONES_TB (
    FIDE_CANTONES_ID_CANTON_PK   NUMBER,
    NOMBRE_CANTON                VARCHAR2(100) NOT NULL,
    FIDE_CANTONES_ID_PROVINCIA_FK NUMBER,
    FIDE_CANTONES_ID_ESTADO_FK   NUMBER,
    CONSTRAINT FIDE_CANTONES_ID_CANTON_PK PRIMARY KEY (FIDE_CANTONES_ID_CANTON_PK),
    CONSTRAINT FIDE_CANTONES_ID_PROVINCIA_FK FOREIGN KEY (FIDE_CANTONES_ID_PROVINCIA_FK)
        REFERENCES FIDE_PROVINCIAS_TB(FIDE_PROVINCIAS_ID_PROVINCIA_PK),
    CONSTRAINT FIDE_CANTONES_ID_ESTADO_FK FOREIGN KEY (FIDE_CANTONES_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK)
);

CREATE INDEX FIDE_CANTONES_NOMBRE_IDX ON FIDE_CANTONES_TB (NOMBRE_CANTON);
CREATE INDEX FIDE_CANTONES_PROVINCIA_IDX ON FIDE_CANTONES_TB (FIDE_CANTONES_ID_PROVINCIA_FK);

-- Tabla de Distritos
CREATE TABLE FIDE_DISTRITOS_TB (
    FIDE_DISTRITOS_ID_DISTRITO_PK NUMBER,
    NOMBRE_DISTRITO               VARCHAR2(100) NOT NULL,
    FIDE_DISTRITOS_ID_CANTON_FK   NUMBER,
    FIDE_DISTRITOS_ID_ESTADO_FK   NUMBER,
    CONSTRAINT FIDE_DISTRITOS_ID_DISTRITO_PK PRIMARY KEY (FIDE_DISTRITOS_ID_DISTRITO_PK),
    CONSTRAINT FIDE_DISTRITOS_ID_CANTON_FK FOREIGN KEY (FIDE_DISTRITOS_ID_CANTON_FK)
        REFERENCES FIDE_CANTONES_TB(FIDE_CANTONES_ID_CANTON_PK),
    CONSTRAINT FIDE_DISTRITOS_ID_ESTADO_FK FOREIGN KEY (FIDE_DISTRITOS_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK)
);

CREATE INDEX FIDE_DISTRITOS_NOMBRE_IDX ON FIDE_DISTRITOS_TB (NOMBRE_DISTRITO);
CREATE INDEX FIDE_DISTRITOS_CANTON_IDX ON FIDE_DISTRITOS_TB (FIDE_DISTRITOS_ID_CANTON_FK);

-- Tabla de Direcciones
CREATE TABLE FIDE_DIRECCIONES_TB (
    FIDE_DIRECCIONES_ID_DIRECCION_PK NUMBER,
    DETALLE                          VARCHAR2(400) NOT NULL,
    CODIGO_POSTAL                    VARCHAR2(20),
    FIDE_DIRECCIONES_ID_DISTRITO_FK  NUMBER,
    FIDE_DIRECCIONES_ID_ESTADO_FK    NUMBER,
    CONSTRAINT FIDE_DIRECCIONES_ID_DIRECCION_PK PRIMARY KEY (FIDE_DIRECCIONES_ID_DIRECCION_PK),
    CONSTRAINT FIDE_DIRECCIONES_ID_DISTRITO_FK FOREIGN KEY (FIDE_DIRECCIONES_ID_DISTRITO_FK)
        REFERENCES FIDE_DISTRITOS_TB(FIDE_DISTRITOS_ID_DISTRITO_PK),
    CONSTRAINT FIDE_DIRECCIONES_ID_ESTADO_FK FOREIGN KEY (FIDE_DIRECCIONES_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK)
);

CREATE INDEX FIDE_DIRECCIONES_DISTRITO_IDX ON FIDE_DIRECCIONES_TB (FIDE_DIRECCIONES_ID_DISTRITO_FK);
CREATE INDEX FIDE_DIRECCIONES_CODIGO_POSTAL_IDX ON FIDE_DIRECCIONES_TB (CODIGO_POSTAL);

-- Tabla de Puestos
CREATE TABLE FIDE_PUESTOS_TB (
    FIDE_PUESTOS_ID_PUESTO_PK   NUMBER,
    NOMBRE_PUESTO               VARCHAR2(100) NOT NULL,
    SALARIO_BASE                 NUMBER(10,2) NOT NULL,
    DESCRIPCION                  VARCHAR2(250),
    FIDE_PUESTOS_ID_ESTADO_FK   NUMBER,
    CONSTRAINT FIDE_PUESTOS_ID_PUESTO_PK PRIMARY KEY (FIDE_PUESTOS_ID_PUESTO_PK),
    CONSTRAINT FIDE_PUESTOS_ID_ESTADO_FK FOREIGN KEY (FIDE_PUESTOS_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK)
);

CREATE INDEX FIDE_PUESTOS_NOMBRE_IDX ON FIDE_PUESTOS_TB (NOMBRE_PUESTO);
CREATE INDEX FIDE_PUESTOS_SALARIO_IDX ON FIDE_PUESTOS_TB (SALARIO_BASE);

-- Tabla de Sucursales
CREATE TABLE FIDE_SUCURSALES_TB (
    FIDE_SUCURSALES_ID_SUCURSAL_PK   NUMBER,
    NOMBRE_SUCURSAL                  VARCHAR2(150) NOT NULL,
    TELEFONO                         VARCHAR2(20),
    FECHA_APERTURA                   DATE DEFAULT SYSDATE,
    FIDE_SUCURSALES_ID_DIRECCION_FK  NUMBER,
    FIDE_SUCURSALES_ID_ESTADO_FK     NUMBER,
    CONSTRAINT FIDE_SUCURSALES_ID_SUCURSAL_PK PRIMARY KEY (FIDE_SUCURSALES_ID_SUCURSAL_PK),
    CONSTRAINT FIDE_SUCURSALES_ID_DIRECCION_FK FOREIGN KEY (FIDE_SUCURSALES_ID_DIRECCION_FK)
        REFERENCES FIDE_DIRECCIONES_TB(FIDE_DIRECCIONES_ID_DIRECCION_PK),
    CONSTRAINT FIDE_SUCURSALES_ID_ESTADO_FK FOREIGN KEY (FIDE_SUCURSALES_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK)
);

CREATE INDEX FIDE_SUCURSALES_NOMBRE_IDX ON FIDE_SUCURSALES_TB (NOMBRE_SUCURSAL);
CREATE INDEX FIDE_SUCURSALES_DIRECCION_IDX ON FIDE_SUCURSALES_TB (FIDE_SUCURSALES_ID_DIRECCION_FK);

-- Tabla de Correos
CREATE TABLE FIDE_CORREOS_TB (
    FIDE_CORREOS_ID_CORREO_PK   NUMBER,
    CORREO                      VARCHAR2(150) NOT NULL,
    TIPO_CORREO                 VARCHAR2(50) DEFAULT 'PERSONAL',
    FIDE_CORREOS_ID_ESTADO_FK   NUMBER,
    CONSTRAINT FIDE_CORREOS_ID_CORREO_PK PRIMARY KEY (FIDE_CORREOS_ID_CORREO_PK),
    CONSTRAINT FIDE_CORREOS_ID_ESTADO_FK FOREIGN KEY (FIDE_CORREOS_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK)
);

CREATE UNIQUE INDEX FIDE_CORREOS_CORREO_IDX ON FIDE_CORREOS_TB (CORREO);
CREATE INDEX FIDE_CORREOS_TIPO_IDX ON FIDE_CORREOS_TB (TIPO_CORREO);

-- Tabla de Teléfonos
CREATE TABLE FIDE_TELEFONOS_TB (
    FIDE_TELEFONOS_ID_TELEFONO_PK   NUMBER,
    TELEFONO                        VARCHAR2(20) NOT NULL,
    TIPO_TELEFONO                   VARCHAR2(50) DEFAULT 'MOVIL',
    FIDE_TELEFONOS_ID_ESTADO_FK     NUMBER,
    CONSTRAINT FIDE_TELEFONOS_ID_TELEFONO_PK PRIMARY KEY (FIDE_TELEFONOS_ID_TELEFONO_PK),
    CONSTRAINT FIDE_TELEFONOS_ID_ESTADO_FK FOREIGN KEY (FIDE_TELEFONOS_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK)
);

CREATE UNIQUE INDEX FIDE_TELEFONOS_TELEFONO_IDX ON FIDE_TELEFONOS_TB (TELEFONO);
CREATE INDEX FIDE_TELEFONOS_TIPO_IDX ON FIDE_TELEFONOS_TB (TIPO_TELEFONO);

-- Tabla de Usuarios
CREATE TABLE FIDE_USUARIOS_TB (
    FIDE_USUARIOS_ID_USUARIO_PK   NUMBER,
    CEDULA                        VARCHAR2(20) NOT NULL,
    NOMBRE                        VARCHAR2(100) NOT NULL,
    APELLIDO_PATERNO              VARCHAR2(100) NOT NULL,
    APELLIDO_MATERNO              VARCHAR2(100),
    FECHA_NACIMIENTO              DATE,
    CONTRASENA                    VARCHAR2(100) NOT NULL,
   
    FIDE_USUARIOS_ID_CORREO_FK    NUMBER,
    FIDE_USUARIOS_ID_TELEFONO_FK  NUMBER,
    FIDE_USUARIOS_ID_DIRECCION_FK NUMBER,
    FIDE_USUARIOS_ID_PUESTO_FK    NUMBER,
    FIDE_USUARIOS_ID_SUCURSAL_FK  NUMBER,
    FIDE_USUARIOS_ID_ESTADO_FK    NUMBER,

    TIPO_USUARIO                  VARCHAR2(50) NOT NULL,
    FECHA_REGISTRO                DATE DEFAULT SYSDATE,
    ULTIMO_ACCESO                 DATE,
    SALARIO                       NUMBER(10,2),
    FECHA_CONTRATACION            DATE,
    PUNTOS_LEALTAD                NUMBER DEFAULT 0,

    CONSTRAINT FIDE_USUARIOS_ID_USUARIO_PK PRIMARY KEY (FIDE_USUARIOS_ID_USUARIO_PK),
    CONSTRAINT FIDE_USUARIOS_ID_CORREO_FK FOREIGN KEY (FIDE_USUARIOS_ID_CORREO_FK)
        REFERENCES FIDE_CORREOS_TB(FIDE_CORREOS_ID_CORREO_PK),
    CONSTRAINT FIDE_USUARIOS_ID_TELEFONO_FK FOREIGN KEY (FIDE_USUARIOS_ID_TELEFONO_FK)
        REFERENCES FIDE_TELEFONOS_TB(FIDE_TELEFONOS_ID_TELEFONO_PK),
    CONSTRAINT FIDE_USUARIOS_ID_DIRECCION_FK FOREIGN KEY (FIDE_USUARIOS_ID_DIRECCION_FK)
        REFERENCES FIDE_DIRECCIONES_TB(FIDE_DIRECCIONES_ID_DIRECCION_PK),
    CONSTRAINT FIDE_USUARIOS_ID_PUESTO_FK FOREIGN KEY (FIDE_USUARIOS_ID_PUESTO_FK)
        REFERENCES FIDE_PUESTOS_TB(FIDE_PUESTOS_ID_PUESTO_PK),
    CONSTRAINT FIDE_USUARIOS_ID_SUCURSAL_FK FOREIGN KEY (FIDE_USUARIOS_ID_SUCURSAL_FK)
        REFERENCES FIDE_SUCURSALES_TB(FIDE_SUCURSALES_ID_SUCURSAL_PK),
    CONSTRAINT FIDE_USUARIOS_ID_ESTADO_FK FOREIGN KEY (FIDE_USUARIOS_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK),
    CONSTRAINT FIDE_USUARIOS_CHK_TIPO_USUARIO CHECK (TIPO_USUARIO IN ('ADMIN', 'GERENTE', 'EMPLEADO', 'CLIENTE'))
);

CREATE UNIQUE INDEX FIDE_USUARIOS_CEDULA_IDX ON FIDE_USUARIOS_TB (CEDULA);
CREATE INDEX FIDE_USUARIOS_TIPO_IDX ON FIDE_USUARIOS_TB (TIPO_USUARIO);
CREATE INDEX FIDE_USUARIOS_SUCURSAL_IDX ON FIDE_USUARIOS_TB (FIDE_USUARIOS_ID_SUCURSAL_FK);
CREATE INDEX FIDE_USUARIOS_PUESTO_IDX ON FIDE_USUARIOS_TB (FIDE_USUARIOS_ID_PUESTO_FK);
CREATE INDEX FIDE_USUARIOS_NOMBRE_IDX ON FIDE_USUARIOS_TB (NOMBRE, APELLIDO_PATERNO);

-- Tabla de Proveedores
CREATE TABLE FIDE_PROVEEDORES_TB (
    FIDE_PROVEEDORES_ID_PROVEEDOR_PK NUMBER,
    NOMBRE_PROVEEDOR               VARCHAR2(150) NOT NULL,
    CONTACTO                       VARCHAR2(100),
    DESCRIPCION                    VARCHAR2(250),
    FIDE_PROVEEDORES_ID_CORREO_FK  NUMBER,
    FIDE_PROVEEDORES_ID_TELEFONO_FK NUMBER,
    FIDE_PROVEEDORES_ID_DIRECCION_FK NUMBER,
    FIDE_PROVEEDORES_ID_ESTADO_FK  NUMBER,
    CONSTRAINT FIDE_PROVEEDORES_ID_PROVEEDOR_PK PRIMARY KEY (FIDE_PROVEEDORES_ID_PROVEEDOR_PK),
    CONSTRAINT FIDE_PROVEEDORES_ID_CORREO_FK FOREIGN KEY (FIDE_PROVEEDORES_ID_CORREO_FK)
        REFERENCES FIDE_CORREOS_TB(FIDE_CORREOS_ID_CORREO_PK),
    CONSTRAINT FIDE_PROVEEDORES_ID_TELEFONO_FK FOREIGN KEY (FIDE_PROVEEDORES_ID_TELEFONO_FK)
        REFERENCES FIDE_TELEFONOS_TB(FIDE_TELEFONOS_ID_TELEFONO_PK),
    CONSTRAINT FIDE_PROVEEDORES_ID_DIRECCION_FK FOREIGN KEY (FIDE_PROVEEDORES_ID_DIRECCION_FK)
        REFERENCES FIDE_DIRECCIONES_TB(FIDE_DIRECCIONES_ID_DIRECCION_PK),
    CONSTRAINT FIDE_PROVEEDORES_ID_ESTADO_FK FOREIGN KEY (FIDE_PROVEEDORES_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK)
);

CREATE INDEX FIDE_PROVEEDORES_NOMBRE_IDX ON FIDE_PROVEEDORES_TB (NOMBRE_PROVEEDOR);
CREATE INDEX FIDE_PROVEEDORES_CONTACTO_IDX ON FIDE_PROVEEDORES_TB (CONTACTO);

-- Tabla de Categorías
CREATE TABLE FIDE_CATEGORIAS_TB (
    FIDE_CATEGORIAS_ID_CATEGORIA_PK NUMBER,
    NOMBRE_CATEGORIA              VARCHAR2(100) NOT NULL,
    DESCRIPCION                   VARCHAR2(250),
    FIDE_CATEGORIAS_ID_ESTADO_FK  NUMBER,
    CONSTRAINT FIDE_CATEGORIAS_ID_CATEGORIA_PK PRIMARY KEY (FIDE_CATEGORIAS_ID_CATEGORIA_PK),
    CONSTRAINT FIDE_CATEGORIAS_ID_ESTADO_FK FOREIGN KEY (FIDE_CATEGORIAS_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK)
);

CREATE INDEX FIDE_CATEGORIAS_NOMBRE_IDX ON FIDE_CATEGORIAS_TB (NOMBRE_CATEGORIA);

-- Tabla de Productos
CREATE TABLE FIDE_PRODUCTOS_TB (
    FIDE_PRODUCTOS_ID_PRODUCTO_PK   NUMBER,
    NOMBRE_PRODUCTO                 VARCHAR2(150) NOT NULL,
    DESCRIPCION                     VARCHAR2(250),
    PRECIO_UNITARIO                 NUMBER(10,2) NOT NULL,
    FECHA_VENCIMIENTO               DATE,
    STOCK_MINIMO                    NUMBER DEFAULT 0,
    FIDE_PRODUCTOS_ID_CATEGORIA_FK  NUMBER,
    FIDE_PRODUCTOS_ID_PROVEEDOR_FK  NUMBER,
    FIDE_PRODUCTOS_ID_ESTADO_FK     NUMBER,
    CONSTRAINT FIDE_PRODUCTOS_ID_PRODUCTO_PK PRIMARY KEY (FIDE_PRODUCTOS_ID_PRODUCTO_PK),
    CONSTRAINT FIDE_PRODUCTOS_ID_CATEGORIA_FK FOREIGN KEY (FIDE_PRODUCTOS_ID_CATEGORIA_FK)
        REFERENCES FIDE_CATEGORIAS_TB(FIDE_CATEGORIAS_ID_CATEGORIA_PK),
    CONSTRAINT FIDE_PRODUCTOS_ID_PROVEEDOR_FK FOREIGN KEY (FIDE_PRODUCTOS_ID_PROVEEDOR_FK)
        REFERENCES FIDE_PROVEEDORES_TB(FIDE_PROVEEDORES_ID_PROVEEDOR_PK),
    CONSTRAINT FIDE_PRODUCTOS_ID_ESTADO_FK FOREIGN KEY (FIDE_PRODUCTOS_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK)
);

CREATE INDEX FIDE_PRODUCTOS_NOMBRE_IDX ON FIDE_PRODUCTOS_TB (NOMBRE_PRODUCTO);
CREATE INDEX FIDE_PRODUCTOS_CATEGORIA_IDX ON FIDE_PRODUCTOS_TB (FIDE_PRODUCTOS_ID_CATEGORIA_FK);
CREATE INDEX FIDE_PRODUCTOS_PROVEEDOR_IDX ON FIDE_PRODUCTOS_TB (FIDE_PRODUCTOS_ID_PROVEEDOR_FK);
CREATE INDEX FIDE_PRODUCTOS_PRECIO_IDX ON FIDE_PRODUCTOS_TB (PRECIO_UNITARIO);
CREATE INDEX FIDE_PRODUCTOS_VENCIMIENTO_IDX ON FIDE_PRODUCTOS_TB (FECHA_VENCIMIENTO);

-- Tabla de Inventarios
CREATE TABLE FIDE_INVENTARIOS_TB (
    FIDE_INVENTARIOS_ID_INVENTARIO_PK NUMBER,
    CANTIDAD_STOCK NUMBER NOT NULL,
    CANTIDAD_MINIMA NUMBER,
    FECHA_ACTUALIZACION DATE DEFAULT SYSDATE,
    FIDE_INVENTARIOS_ID_PRODUCTO_FK NUMBER NOT NULL,
    FIDE_INVENTARIOS_ID_SUCURSAL_FK NUMBER NOT NULL,
    FIDE_INVENTARIOS_ID_ESTADO_FK NUMBER,
    
    -- PK COMPUESTA (2 columnas)
    CONSTRAINT FIDE_INVENTARIOS_PK PRIMARY KEY (
        FIDE_INVENTARIOS_ID_PRODUCTO_FK, 
        FIDE_INVENTARIOS_ID_SUCURSAL_FK
    ),
    
    CONSTRAINT FIDE_INVENTARIOS_ID_PRODUCTO_FK FOREIGN KEY (FIDE_INVENTARIOS_ID_PRODUCTO_FK)
        REFERENCES FIDE_PRODUCTOS_TB(FIDE_PRODUCTOS_ID_PRODUCTO_PK),
    CONSTRAINT FIDE_INVENTARIOS_ID_SUCURSAL_FK FOREIGN KEY (FIDE_INVENTARIOS_ID_SUCURSAL_FK)
        REFERENCES FIDE_SUCURSALES_TB(FIDE_SUCURSALES_ID_SUCURSAL_PK),
    CONSTRAINT FIDE_INVENTARIOS_ID_ESTADO_FK FOREIGN KEY (FIDE_INVENTARIOS_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK)
);

-- Tabla de Descuentos
CREATE TABLE FIDE_DESCUENTOS_TB (
    FIDE_DESCUENTOS_ID_DESCUENTO_PK   NUMBER,
    NOMBRE_DESCUENTO                  VARCHAR2(150) NOT NULL,
    PORCENTAJE                        NUMBER(5,2) NOT NULL,
    DESCRIPCION                       VARCHAR2(300),
    FECHA_INICIO                      DATE NOT NULL,
    FECHA_FIN                         DATE NOT NULL,
    FIDE_DESCUENTOS_ID_ESTADO_FK      NUMBER,
    CONSTRAINT FIDE_DESCUENTOS_ID_DESCUENTO_PK PRIMARY KEY (FIDE_DESCUENTOS_ID_DESCUENTO_PK),
    CONSTRAINT FIDE_DESCUENTOS_ID_ESTADO_FK FOREIGN KEY (FIDE_DESCUENTOS_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK)
);

CREATE INDEX FIDE_DESCUENTOS_NOMBRE_IDX ON FIDE_DESCUENTOS_TB (NOMBRE_DESCUENTO);
CREATE INDEX FIDE_DESCUENTOS_FECHAS_IDX ON FIDE_DESCUENTOS_TB (FECHA_INICIO, FECHA_FIN);

-- Tabla de Promociones
CREATE TABLE FIDE_PROMOCIONES_TB (
    FIDE_PROMOCIONES_ID_PROMOCION_PK NUMBER,
    NOMBRE_PROMOCION                VARCHAR2(150) NOT NULL,
    DESCRIPCION                     VARCHAR2(300),
    FECHA_INICIO                    DATE NOT NULL,
    FECHA_FIN                       DATE NOT NULL,
    TIPO_PROMOCION                  VARCHAR2(50),
    FIDE_PROMOCIONES_ID_PRODUCTO_FK NUMBER,
    FIDE_PROMOCIONES_ID_DESCUENTO_FK NUMBER,
    FIDE_PROMOCIONES_ID_ESTADO_FK   NUMBER,
    CONSTRAINT FIDE_PROMOCIONES_ID_PROMOCION_PK PRIMARY KEY (FIDE_PROMOCIONES_ID_PROMOCION_PK),
    CONSTRAINT FIDE_PROMOCIONES_ID_PRODUCTO_FK FOREIGN KEY (FIDE_PROMOCIONES_ID_PRODUCTO_FK)
        REFERENCES FIDE_PRODUCTOS_TB(FIDE_PRODUCTOS_ID_PRODUCTO_PK),
    CONSTRAINT FIDE_PROMOCIONES_ID_DESCUENTO_FK FOREIGN KEY (FIDE_PROMOCIONES_ID_DESCUENTO_FK)
        REFERENCES FIDE_DESCUENTOS_TB(FIDE_DESCUENTOS_ID_DESCUENTO_PK),
    CONSTRAINT FIDE_PROMOCIONES_ID_ESTADO_FK FOREIGN KEY (FIDE_PROMOCIONES_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK)
);

CREATE INDEX FIDE_PROMOCIONES_NOMBRE_IDX ON FIDE_PROMOCIONES_TB (NOMBRE_PROMOCION);
CREATE INDEX FIDE_PROMOCIONES_FECHAS_IDX ON FIDE_PROMOCIONES_TB (FECHA_INICIO, FECHA_FIN);
CREATE INDEX FIDE_PROMOCIONES_PRODUCTO_IDX ON FIDE_PROMOCIONES_TB (FIDE_PROMOCIONES_ID_PRODUCTO_FK);

-- Tabla de Compras
CREATE TABLE FIDE_COMPRAS_TB (
    FIDE_COMPRAS_ID_COMPRA_PK      NUMBER,
    NUMERO_ORDEN                   VARCHAR2(50) NOT NULL,
    FECHA_ORDEN                    DATE DEFAULT SYSDATE,
    FECHA_ESTIMADA_ENTREGA         DATE,
    FECHA_RECEPCION                DATE,
    TOTAL_COMPRA                   NUMBER(10,2),
    ESTADO_COMPRA                  VARCHAR2(50) DEFAULT 'PENDIENTE',
    FIDE_COMPRAS_ID_PROVEEDOR_FK   NUMBER,
    FIDE_COMPRAS_ID_SUCURSAL_FK    NUMBER,
    FIDE_COMPRAS_ID_EMPLEADO_FK    NUMBER,
    FIDE_COMPRAS_ID_ESTADO_FK      NUMBER,
    CONSTRAINT FIDE_COMPRAS_ID_COMPRA_PK PRIMARY KEY (FIDE_COMPRAS_ID_COMPRA_PK),
    CONSTRAINT FIDE_COMPRAS_ID_PROVEEDOR_FK FOREIGN KEY (FIDE_COMPRAS_ID_PROVEEDOR_FK)
        REFERENCES FIDE_PROVEEDORES_TB(FIDE_PROVEEDORES_ID_PROVEEDOR_PK),
    CONSTRAINT FIDE_COMPRAS_ID_SUCURSAL_FK FOREIGN KEY (FIDE_COMPRAS_ID_SUCURSAL_FK)
        REFERENCES FIDE_SUCURSALES_TB(FIDE_SUCURSALES_ID_SUCURSAL_PK),
    CONSTRAINT FIDE_COMPRAS_ID_EMPLEADO_FK FOREIGN KEY (FIDE_COMPRAS_ID_EMPLEADO_FK)
        REFERENCES FIDE_USUARIOS_TB(FIDE_USUARIOS_ID_USUARIO_PK),
    CONSTRAINT FIDE_COMPRAS_ID_ESTADO_FK FOREIGN KEY (FIDE_COMPRAS_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK),
    CONSTRAINT FIDE_COMPRAS_ORDEN_PROVEEDOR_UK UNIQUE (NUMERO_ORDEN, FIDE_COMPRAS_ID_PROVEEDOR_FK)
);

CREATE UNIQUE INDEX FIDE_COMPRAS_NUMERO_ORDEN_IDX ON FIDE_COMPRAS_TB (NUMERO_ORDEN);
CREATE INDEX FIDE_COMPRAS_PROVEEDOR_IDX ON FIDE_COMPRAS_TB (FIDE_COMPRAS_ID_PROVEEDOR_FK);
CREATE INDEX FIDE_COMPRAS_SUCURSAL_IDX ON FIDE_COMPRAS_TB (FIDE_COMPRAS_ID_SUCURSAL_FK);
CREATE INDEX FIDE_COMPRAS_FECHA_ORDEN_IDX ON FIDE_COMPRAS_TB (FECHA_ORDEN);
CREATE INDEX FIDE_COMPRAS_ESTADO_IDX ON FIDE_COMPRAS_TB (ESTADO_COMPRA);

-- Tabla de Detalles de Compra
CREATE TABLE FIDE_DETALLES_COMPRA_TB (
    FIDE_DETALLES_COMPRA_ID_DETALLE_PK NUMBER,
    CANTIDAD                         NUMBER NOT NULL,
    PRECIO_UNITARIO                  NUMBER(10,2) NOT NULL,
    SUBTOTAL                         NUMBER(10,2),
    FIDE_DETALLES_COMPRA_ID_COMPRA_FK NUMBER NOT NULL,
    FIDE_DETALLES_COMPRA_ID_PRODUCTO_FK NUMBER NOT NULL,
    FIDE_DETALLES_COMPRA_ID_ESTADO_FK NUMBER,
    CONSTRAINT FIDE_DETALLES_COMPRA_ID_DETALLE_PK PRIMARY KEY (FIDE_DETALLES_COMPRA_ID_DETALLE_PK),
    CONSTRAINT FIDE_DETALLES_COMPRA_ID_COMPRA_FK FOREIGN KEY (FIDE_DETALLES_COMPRA_ID_COMPRA_FK)
        REFERENCES FIDE_COMPRAS_TB(FIDE_COMPRAS_ID_COMPRA_PK),
    CONSTRAINT FIDE_DETALLES_COMPRA_ID_PRODUCTO_FK FOREIGN KEY (FIDE_DETALLES_COMPRA_ID_PRODUCTO_FK)
        REFERENCES FIDE_PRODUCTOS_TB(FIDE_PRODUCTOS_ID_PRODUCTO_PK),
    CONSTRAINT FIDE_DETALLES_COMPRA_ID_ESTADO_FK FOREIGN KEY (FIDE_DETALLES_COMPRA_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK),
    CONSTRAINT FIDE_DETALLES_COMPRA_COMPRA_PRODUCTO_UK UNIQUE (FIDE_DETALLES_COMPRA_ID_COMPRA_FK, FIDE_DETALLES_COMPRA_ID_PRODUCTO_FK)
);

CREATE INDEX FIDE_DETALLES_COMPRA_COMPRA_IDX ON FIDE_DETALLES_COMPRA_TB (FIDE_DETALLES_COMPRA_ID_COMPRA_FK);
CREATE INDEX FIDE_DETALLES_COMPRA_PRODUCTO_IDX ON FIDE_DETALLES_COMPRA_TB (FIDE_DETALLES_COMPRA_ID_PRODUCTO_FK);

-- Tabla de Facturas
CREATE TABLE FIDE_FACTURAS_TB (
    FIDE_FACTURAS_ID_FACTURA_PK    NUMBER,
    NUMERO_FACTURA                 VARCHAR2(50) NOT NULL,
    FECHA_FACTURA                  DATE DEFAULT SYSDATE,
    SUBTOTAL                       NUMBER(10,2),
    IMPUESTO                       NUMBER(10,2),
    DESCUENTO_TOTAL                NUMBER(10,2),
    TOTAL                          NUMBER(10,2),
    TIPO_PAGO                      VARCHAR2(50),
    FIDE_FACTURAS_ID_CLIENTE_FK    NUMBER,
    FIDE_FACTURAS_ID_EMPLEADO_FK   NUMBER,
    FIDE_FACTURAS_ID_SUCURSAL_FK   NUMBER,
    FIDE_FACTURAS_ID_ESTADO_FK     NUMBER,
    CONSTRAINT FIDE_FACTURAS_ID_FACTURA_PK PRIMARY KEY (FIDE_FACTURAS_ID_FACTURA_PK),
    CONSTRAINT FIDE_FACTURAS_ID_CLIENTE_FK FOREIGN KEY (FIDE_FACTURAS_ID_CLIENTE_FK)
        REFERENCES FIDE_USUARIOS_TB(FIDE_USUARIOS_ID_USUARIO_PK),
    CONSTRAINT FIDE_FACTURAS_ID_EMPLEADO_FK FOREIGN KEY (FIDE_FACTURAS_ID_EMPLEADO_FK)
        REFERENCES FIDE_USUARIOS_TB(FIDE_USUARIOS_ID_USUARIO_PK),
    CONSTRAINT FIDE_FACTURAS_ID_SUCURSAL_FK FOREIGN KEY (FIDE_FACTURAS_ID_SUCURSAL_FK)
        REFERENCES FIDE_SUCURSALES_TB(FIDE_SUCURSALES_ID_SUCURSAL_PK),
    CONSTRAINT FIDE_FACTURAS_ID_ESTADO_FK FOREIGN KEY (FIDE_FACTURAS_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK),
    CONSTRAINT FIDE_FACTURAS_NUMERO_SUCURSAL_UK UNIQUE (NUMERO_FACTURA, FIDE_FACTURAS_ID_SUCURSAL_FK)
);

CREATE UNIQUE INDEX FIDE_FACTURAS_NUMERO_FACTURA_IDX ON FIDE_FACTURAS_TB (NUMERO_FACTURA);
CREATE INDEX FIDE_FACTURAS_CLIENTE_IDX ON FIDE_FACTURAS_TB (FIDE_FACTURAS_ID_CLIENTE_FK);
CREATE INDEX FIDE_FACTURAS_EMPLEADO_IDX ON FIDE_FACTURAS_TB (FIDE_FACTURAS_ID_EMPLEADO_FK);
CREATE INDEX FIDE_FACTURAS_SUCURSAL_IDX ON FIDE_FACTURAS_TB (FIDE_FACTURAS_ID_SUCURSAL_FK);
CREATE INDEX FIDE_FACTURAS_FECHA_IDX ON FIDE_FACTURAS_TB (FECHA_FACTURA);

-- Tabla de Detalles de Factura
CREATE TABLE FIDE_DETALLES_FACTURA_TB (
    FIDE_DETALLES_FACTURA_ID_DETALLE_PK NUMBER,
    CANTIDAD                            NUMBER NOT NULL,
    PRECIO_UNITARIO                     NUMBER(10,2) NOT NULL,
    SUBTOTAL                            NUMBER(10,2),
    DESCUENTO_APLICADO                  NUMBER(10,2) DEFAULT 0,
    FIDE_DETALLES_FACTURA_ID_PRODUCTO_FK NUMBER NOT NULL,
    FIDE_DETALLES_FACTURA_ID_FACTURA_FK  NUMBER NOT NULL,
    FIDE_DETALLES_FACTURA_ID_ESTADO_FK  NUMBER,
    CONSTRAINT FIDE_DETALLES_FACTURA_ID_DETALLE_PK PRIMARY KEY (FIDE_DETALLES_FACTURA_ID_DETALLE_PK),
    CONSTRAINT FIDE_DETALLES_FACTURA_ID_PRODUCTO_FK FOREIGN KEY (FIDE_DETALLES_FACTURA_ID_PRODUCTO_FK)
        REFERENCES FIDE_PRODUCTOS_TB(FIDE_PRODUCTOS_ID_PRODUCTO_PK),
    CONSTRAINT FIDE_DETALLES_FACTURA_ID_FACTURA_FK FOREIGN KEY (FIDE_DETALLES_FACTURA_ID_FACTURA_FK)
        REFERENCES FIDE_FACTURAS_TB(FIDE_FACTURAS_ID_FACTURA_PK),
    CONSTRAINT FIDE_DETALLES_FACTURA_ID_ESTADO_FK FOREIGN KEY (FIDE_DETALLES_FACTURA_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK),
    CONSTRAINT FIDE_DETALLES_FACTURA_FACTURA_PRODUCTO_UK UNIQUE (FIDE_DETALLES_FACTURA_ID_FACTURA_FK, FIDE_DETALLES_FACTURA_ID_PRODUCTO_FK)
);

CREATE INDEX FIDE_DETALLES_FACTURA_FACTURA_IDX ON FIDE_DETALLES_FACTURA_TB (FIDE_DETALLES_FACTURA_ID_FACTURA_FK);
CREATE INDEX FIDE_DETALLES_FACTURA_PRODUCTO_IDX ON FIDE_DETALLES_FACTURA_TB (FIDE_DETALLES_FACTURA_ID_PRODUCTO_FK);

-- Tabla de Clientes Descuento
CREATE TABLE FIDE_CLIENTES_DESCUENTO_TB (
    FIDE_CLIENTES_DESCUENTO_ID_CLIENTE_DESCUENTO_PK NUMBER,
    FECHA_ASIGNACION               DATE DEFAULT SYSDATE,
    PUNTOS_UTILIZADOS              NUMBER DEFAULT 0,
    FIDE_CLIENTES_DESCUENTO_ID_USUARIO_FK NUMBER NOT NULL,
    FIDE_CLIENTES_DESCUENTO_ID_DESCUENTO_FK NUMBER NOT NULL,
    FIDE_CLIENTES_DESCUENTO_ID_PROMOCION_FK NUMBER,
    FIDE_CLIENTES_DESCUENTO_ID_ESTADO_FK NUMBER,
    CONSTRAINT FIDE_CLIENTES_DESCUENTO_ID_CLIENTE_DESCUENTO_PK PRIMARY KEY (FIDE_CLIENTES_DESCUENTO_ID_CLIENTE_DESCUENTO_PK),
    CONSTRAINT FIDE_CLIENTES_DESCUENTO_ID_USUARIO_FK FOREIGN KEY (FIDE_CLIENTES_DESCUENTO_ID_USUARIO_FK)
        REFERENCES FIDE_USUARIOS_TB(FIDE_USUARIOS_ID_USUARIO_PK),
    CONSTRAINT FIDE_CLIENTES_DESCUENTO_ID_DESCUENTO_FK FOREIGN KEY (FIDE_CLIENTES_DESCUENTO_ID_DESCUENTO_FK)
        REFERENCES FIDE_DESCUENTOS_TB(FIDE_DESCUENTOS_ID_DESCUENTO_PK),
    CONSTRAINT FIDE_CLIENTES_DESCUENTO_ID_PROMOCION_FK FOREIGN KEY (FIDE_CLIENTES_DESCUENTO_ID_PROMOCION_FK)
        REFERENCES FIDE_PROMOCIONES_TB(FIDE_PROMOCIONES_ID_PROMOCION_PK),
    CONSTRAINT FIDE_CLIENTES_DESCUENTO_ID_ESTADO_FK FOREIGN KEY (FIDE_CLIENTES_DESCUENTO_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK),
    CONSTRAINT FIDE_CLIENTES_DESCUENTO_CLIENTE_DESCUENTO_UK UNIQUE (FIDE_CLIENTES_DESCUENTO_ID_USUARIO_FK, FIDE_CLIENTES_DESCUENTO_ID_DESCUENTO_FK)
);

CREATE INDEX FIDE_CLIENTES_DESCUENTO_USUARIO_IDX ON FIDE_CLIENTES_DESCUENTO_TB (FIDE_CLIENTES_DESCUENTO_ID_USUARIO_FK);
CREATE INDEX FIDE_CLIENTES_DESCUENTO_DESCUENTO_IDX ON FIDE_CLIENTES_DESCUENTO_TB (FIDE_CLIENTES_DESCUENTO_ID_DESCUENTO_FK);
CREATE INDEX FIDE_CLIENTES_DESCUENTO_PROMOCION_IDX ON FIDE_CLIENTES_DESCUENTO_TB (FIDE_CLIENTES_DESCUENTO_ID_PROMOCION_FK);

-- Tabla de Planillas
CREATE TABLE FIDE_PLANILLAS_TB (
    FIDE_PLANILLAS_ID_PLANILLA_PK NUMBER,
    MES NUMBER NOT NULL,
    ANIO NUMBER NOT NULL,
    FECHA_GENERACION DATE DEFAULT SYSDATE,
    SALARIO_BRUTO NUMBER(10,2),
    DEDUCCIONES NUMBER(10,2),
    SALARIO_NETO NUMBER(10,2),
    FIDE_PLANILLAS_ID_EMPLEADO_FK NUMBER,
    FIDE_PLANILLAS_ID_SUCURSAL_FK NUMBER,
    FIDE_PLANILLAS_ID_ESTADO_FK NUMBER,
    
    -- PK COMPUESTA (3 columnas)
    CONSTRAINT FIDE_PLANILLAS_PK PRIMARY KEY (
        FIDE_PLANILLAS_ID_EMPLEADO_FK, 
        MES, 
        ANIO
    ),
    
    CONSTRAINT FIDE_PLANILLAS_ID_EMPLEADO_FK FOREIGN KEY (FIDE_PLANILLAS_ID_EMPLEADO_FK)
        REFERENCES FIDE_USUARIOS_TB(FIDE_USUARIOS_ID_USUARIO_PK),
    CONSTRAINT FIDE_PLANILLAS_ID_SUCURSAL_FK FOREIGN KEY (FIDE_PLANILLAS_ID_SUCURSAL_FK)
        REFERENCES FIDE_SUCURSALES_TB(FIDE_SUCURSALES_ID_SUCURSAL_PK),
    CONSTRAINT FIDE_PLANILLAS_ID_ESTADO_FK FOREIGN KEY (FIDE_PLANILLAS_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK)
);

-- Tabla de Asistencia
CREATE TABLE FIDE_ASISTENCIA_TB (
    FIDE_ASISTENCIA_ID_ASISTENCIA_PK NUMBER,
    FECHA_ASISTENCIA DATE DEFAULT SYSDATE,
    HORA_ENTRADA TIMESTAMP,
    HORA_SALIDA TIMESTAMP,
    TIPO_REGISTRO VARCHAR2(50),
    FIDE_ASISTENCIA_ID_EMPLEADO_FK NUMBER NOT NULL,
    FIDE_ASISTENCIA_ID_SUCURSAL_FK NUMBER NOT NULL,
    FIDE_ASISTENCIA_ID_ESTADO_FK NUMBER,
    
    -- PK COMPUESTA (2 columnas)
    CONSTRAINT FIDE_ASISTENCIA_PK PRIMARY KEY (
        FIDE_ASISTENCIA_ID_EMPLEADO_FK, 
        FECHA_ASISTENCIA
    ),
    
    CONSTRAINT FIDE_ASISTENCIA_ID_EMPLEADO_FK FOREIGN KEY (FIDE_ASISTENCIA_ID_EMPLEADO_FK)
        REFERENCES FIDE_USUARIOS_TB(FIDE_USUARIOS_ID_USUARIO_PK),
    CONSTRAINT FIDE_ASISTENCIA_ID_SUCURSAL_FK FOREIGN KEY (FIDE_ASISTENCIA_ID_SUCURSAL_FK)
        REFERENCES FIDE_SUCURSALES_TB(FIDE_SUCURSALES_ID_SUCURSAL_PK),
    CONSTRAINT FIDE_ASISTENCIA_ID_ESTADO_FK FOREIGN KEY (FIDE_ASISTENCIA_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK)
);
-- Tabla de Devoluciones
CREATE TABLE FIDE_DEVOLUCIONES_TB (
    FIDE_DEVOLUCIONES_ID_DEVOLUCION_PK NUMBER,
    FECHA_DEVOLUCION DATE DEFAULT SYSDATE,
    MOTIVO VARCHAR2(250),
    CANTIDAD_DEVUELTA NUMBER,
    MONTO_DEVUELTO NUMBER(10,2),
    FIDE_DEVOLUCIONES_ID_FACTURA_FK NUMBER,
    FIDE_DEVOLUCIONES_ID_PRODUCTO_FK NUMBER,
    FIDE_DEVOLUCIONES_ID_CLIENTE_FK NUMBER,
    FIDE_DEVOLUCIONES_ID_EMPLEADO_FK NUMBER,
    FIDE_DEVOLUCIONES_ID_ESTADO_FK NUMBER,
    CONSTRAINT FIDE_DEVOLUCIONES_ID_DEVOLUCION_PK PRIMARY KEY (FIDE_DEVOLUCIONES_ID_DEVOLUCION_PK),
    CONSTRAINT FIDE_DEVOLUCIONES_ID_FACTURA_FK FOREIGN KEY (FIDE_DEVOLUCIONES_ID_FACTURA_FK)
        REFERENCES FIDE_FACTURAS_TB(FIDE_FACTURAS_ID_FACTURA_PK),
    CONSTRAINT FIDE_DEVOLUCIONES_ID_PRODUCTO_FK FOREIGN KEY (FIDE_DEVOLUCIONES_ID_PRODUCTO_FK)
        REFERENCES FIDE_PRODUCTOS_TB(FIDE_PRODUCTOS_ID_PRODUCTO_PK),
    CONSTRAINT FIDE_DEVOLUCIONES_ID_CLIENTE_FK FOREIGN KEY (FIDE_DEVOLUCIONES_ID_CLIENTE_FK)
        REFERENCES FIDE_USUARIOS_TB(FIDE_USUARIOS_ID_USUARIO_PK),
    CONSTRAINT FIDE_DEVOLUCIONES_ID_EMPLEADO_FK FOREIGN KEY (FIDE_DEVOLUCIONES_ID_EMPLEADO_FK)
        REFERENCES FIDE_USUARIOS_TB(FIDE_USUARIOS_ID_USUARIO_PK),
    CONSTRAINT FIDE_DEVOLUCIONES_ID_ESTADO_FK FOREIGN KEY (FIDE_DEVOLUCIONES_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK)
);

CREATE INDEX FIDE_DEVOLUCIONES_FACTURA_IDX ON FIDE_DEVOLUCIONES_TB (FIDE_DEVOLUCIONES_ID_FACTURA_FK);
CREATE INDEX FIDE_DEVOLUCIONES_PRODUCTO_IDX ON FIDE_DEVOLUCIONES_TB (FIDE_DEVOLUCIONES_ID_PRODUCTO_FK);
CREATE INDEX FIDE_DEVOLUCIONES_CLIENTE_IDX ON FIDE_DEVOLUCIONES_TB (FIDE_DEVOLUCIONES_ID_CLIENTE_FK);
CREATE INDEX FIDE_DEVOLUCIONES_FECHA_IDX ON FIDE_DEVOLUCIONES_TB (FECHA_DEVOLUCION);

-- Tabla de Contratos Proveedores
CREATE TABLE FIDE_CONTRATOS_PROVEEDORES_TB (
    FIDE_CONTRATOS_PROVEEDORES_ID_CONTRATO_PK NUMBER,
    NUMERO_CONTRATO VARCHAR2(50) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE,
    TERMINOS_CONDICIONES VARCHAR2(500),
    MONTO_CONTRATO NUMBER(10,2),
    FIDE_CONTRATOS_PROVEEDORES_ID_PROVEEDOR_FK NUMBER,
    FIDE_CONTRATOS_PROVEEDORES_ID_ESTADO_FK NUMBER,
    CONSTRAINT FIDE_CONTRATOS_PROVEEDORES_ID_CONTRATO_PK PRIMARY KEY (FIDE_CONTRATOS_PROVEEDORES_ID_CONTRATO_PK),
    CONSTRAINT FIDE_CONTRATOS_PROVEEDORES_ID_PROVEEDOR_FK FOREIGN KEY (FIDE_CONTRATOS_PROVEEDORES_ID_PROVEEDOR_FK)
        REFERENCES FIDE_PROVEEDORES_TB(FIDE_PROVEEDORES_ID_PROVEEDOR_PK),
    CONSTRAINT FIDE_CONTRATOS_PROVEEDORES_ID_ESTADO_FK FOREIGN KEY (FIDE_CONTRATOS_PROVEEDORES_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK),
    CONSTRAINT FIDE_CONTRATOS_PROVEEDORES_NUMERO_PROVEEDOR_UK UNIQUE (NUMERO_CONTRATO, FIDE_CONTRATOS_PROVEEDORES_ID_PROVEEDOR_FK)
);

CREATE UNIQUE INDEX FIDE_CONTRATOS_PROVEEDORES_NUMERO_IDX ON FIDE_CONTRATOS_PROVEEDORES_TB (NUMERO_CONTRATO);
CREATE INDEX FIDE_CONTRATOS_PROVEEDORES_PROVEEDOR_IDX ON FIDE_CONTRATOS_PROVEEDORES_TB (FIDE_CONTRATOS_PROVEEDORES_ID_PROVEEDOR_FK);
CREATE INDEX FIDE_CONTRATOS_PROVEEDORES_FECHAS_IDX ON FIDE_CONTRATOS_PROVEEDORES_TB (FECHA_INICIO, FECHA_FIN);

-- Tabla de Pagos Proveedores
CREATE TABLE FIDE_PAGOS_PROVEEDORES_TB (
    FIDE_PAGOS_PROVEEDORES_ID_PAGO_PK NUMBER,
    FECHA_PAGO DATE DEFAULT SYSDATE,
    MONTO_PAGO NUMBER(10,2) NOT NULL,
    METODO_PAGO VARCHAR2(50),
    NUMERO_REFERENCIA VARCHAR2(50),
    FIDE_PAGOS_PROVEEDORES_ID_COMPRA_FK NUMBER,
    FIDE_PAGOS_PROVEEDORES_ID_PROVEEDOR_FK NUMBER,
    FIDE_PAGOS_PROVEEDORES_ID_ESTADO_FK NUMBER,
    CONSTRAINT FIDE_PAGOS_PROVEEDORES_ID_PAGO_PK PRIMARY KEY (FIDE_PAGOS_PROVEEDORES_ID_PAGO_PK),
    CONSTRAINT FIDE_PAGOS_PROVEEDORES_ID_COMPRA_FK FOREIGN KEY (FIDE_PAGOS_PROVEEDORES_ID_COMPRA_FK)
        REFERENCES FIDE_COMPRAS_TB(FIDE_COMPRAS_ID_COMPRA_PK),
    CONSTRAINT FIDE_PAGOS_PROVEEDORES_ID_PROVEEDOR_FK FOREIGN KEY (FIDE_PAGOS_PROVEEDORES_ID_PROVEEDOR_FK)
        REFERENCES FIDE_PROVEEDORES_TB(FIDE_PROVEEDORES_ID_PROVEEDOR_PK),
    CONSTRAINT FIDE_PAGOS_PROVEEDORES_ID_ESTADO_FK FOREIGN KEY (FIDE_PAGOS_PROVEEDORES_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(FIDE_ESTADOS_ID_ESTADO_PK)
);

CREATE INDEX FIDE_PAGOS_PROVEEDORES_COMPRA_IDX ON FIDE_PAGOS_PROVEEDORES_TB (FIDE_PAGOS_PROVEEDORES_ID_COMPRA_FK);
CREATE INDEX FIDE_PAGOS_PROVEEDORES_PROVEEDOR_IDX ON FIDE_PAGOS_PROVEEDORES_TB (FIDE_PAGOS_PROVEEDORES_ID_PROVEEDOR_FK);
CREATE INDEX FIDE_PAGOS_PROVEEDORES_FECHA_IDX ON FIDE_PAGOS_PROVEEDORES_TB (FECHA_PAGO);
