--- Secuencias para las tablas.

CREATE SEQUENCE FIDE_ESTADOS_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_PROVINCIAS_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_CANTONES_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_DISTRITOS_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_DIRECCIONES_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_PUESTOS_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_SUCURSALES_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_CORREOS_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_TELEFONOS_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_USUARIOS_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_PROVEEDORES_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_CATEGORIAS_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_PRODUCTOS_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_INVENTARIOS_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_DESCUENTOS_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_PROMOCIONES_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_COMPRAS_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_DETALLES_COMPRA_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_FACTURAS_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_DETALLES_FACTURA_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_CLIENTES_DESCUENTO_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_PLANILLAS_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_ASISTENCIA_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_DEVOLUCIONES_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_CONTRATOS_PROVEEDORES_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE FIDE_PAGOS_PROVEEDORES_SEQ START WITH 100 INCREMENT BY 1;

--- Atributos de auditoría para todas las tablas.

-- 1. Tabla de estados
ALTER TABLE FIDE_ESTADOS_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 2. Tabla de provincias
ALTER TABLE FIDE_PROVINCIAS_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 3. Tabla de cantones
ALTER TABLE FIDE_CANTONES_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 4. Tabla de distritos
ALTER TABLE FIDE_DISTRITOS_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 5. Tabla de direcciones
ALTER TABLE FIDE_DIRECCIONES_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 6. Tabla de puestos
ALTER TABLE FIDE_PUESTOS_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 7. Tabla de sucursales
ALTER TABLE FIDE_SUCURSALES_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 8. Tabla de correos
ALTER TABLE FIDE_CORREOS_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 9. Tabla de teléfonos
ALTER TABLE FIDE_TELEFONOS_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 10. Tabla de usuarios
ALTER TABLE FIDE_USUARIOS_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 11. Tabla de proveedores
ALTER TABLE FIDE_PROVEEDORES_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 12. Tabla de categorías
ALTER TABLE FIDE_CATEGORIAS_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 13. Tabla de productos
ALTER TABLE FIDE_PRODUCTOS_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 14. Tabla de inventarios
ALTER TABLE FIDE_INVENTARIOS_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 15. Tabla de descuentos
ALTER TABLE FIDE_DESCUENTOS_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 16. Tabla de promociones
ALTER TABLE FIDE_PROMOCIONES_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 17. Tabla de compras
ALTER TABLE FIDE_COMPRAS_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 18. Tabla de detalles de compra
ALTER TABLE FIDE_DETALLES_COMPRA_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 19. Tabla de facturas
ALTER TABLE FIDE_FACTURAS_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 20. Tabla de detalles de factura
ALTER TABLE FIDE_DETALLES_FACTURA_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 21. Tabla de clientes descuento
ALTER TABLE FIDE_CLIENTES_DESCUENTO_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 22. Tabla de planillas
ALTER TABLE FIDE_PLANILLAS_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 23. Tabla de asistencia
ALTER TABLE FIDE_ASISTENCIA_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 24. Tabla de devoluciones
ALTER TABLE FIDE_DEVOLUCIONES_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 25. Tabla de contratos proveedores
ALTER TABLE FIDE_CONTRATOS_PROVEEDORES_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

-- 26. Tabla de pagos proveedores
ALTER TABLE FIDE_PAGOS_PROVEEDORES_TB ADD (
    CREADO_POR VARCHAR2(100),
    MODIFICADO_POR VARCHAR2(100),
    ACCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP
);

--- Triggers de insert para las tablas (secuencia con auditoría.

-- 1. Trigger para FIDE_ESTADOS_TB
CREATE OR REPLACE TRIGGER FIDE_ESTADOS_BI_TRG
BEFORE INSERT ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_ESTADOS_ID_ESTADO_PK := FIDE_ESTADOS_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/

-- 2. Trigger para FIDE_PROVINCIAS_TB
CREATE OR REPLACE TRIGGER FIDE_PROVINCIAS_BI_TRG
BEFORE INSERT ON FIDE_PROVINCIAS_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_PROVINCIAS_ID_PROVINCIA_PK := FIDE_PROVINCIAS_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/

-- 3. Trigger para FIDE_CANTONES_TB
CREATE OR REPLACE TRIGGER FIDE_CANTONES_BI_TRG
BEFORE INSERT ON FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_CANTONES_ID_CANTON_PK := FIDE_CANTONES_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/

-- 4. Trigger para FIDE_DISTRITOS_TB
CREATE OR REPLACE TRIGGER FIDE_DISTRITOS_BI_TRG
BEFORE INSERT ON FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_DISTRITOS_ID_DISTRITO_PK := FIDE_DISTRITOS_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/

-- 5. Trigger para FIDE_DIRECCIONES_TB
CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_BI_TRG
BEFORE INSERT ON FIDE_DIRECCIONES_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_DIRECCIONES_ID_DIRECCION_PK := FIDE_DIRECCIONES_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/

-- 6. Trigger para FIDE_PUESTOS_TB
CREATE OR REPLACE TRIGGER FIDE_PUESTOS_BI_TRG
BEFORE INSERT ON FIDE_PUESTOS_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_PUESTOS_ID_PUESTO_PK := FIDE_PUESTOS_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/

-- 7. Trigger para FIDE_SUCURSALES_TB
CREATE OR REPLACE TRIGGER FIDE_SUCURSALES_BI_TRG
BEFORE INSERT ON FIDE_SUCURSALES_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_SUCURSALES_ID_SUCURSAL_PK := FIDE_SUCURSALES_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/

-- 8. Trigger para FIDE_CORREOS_TB
CREATE OR REPLACE TRIGGER FIDE_CORREOS_BI_TRG
BEFORE INSERT ON FIDE_CORREOS_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_CORREOS_ID_CORREO_PK := FIDE_CORREOS_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/

-- 9. Trigger para FIDE_TELEFONOS_TB
CREATE OR REPLACE TRIGGER FIDE_TELEFONOS_BI_TRG
BEFORE INSERT ON FIDE_TELEFONOS_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_TELEFONOS_ID_TELEFONO_PK := FIDE_TELEFONOS_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/

-- 10. Trigger para FIDE_USUARIOS_TB
CREATE OR REPLACE TRIGGER FIDE_USUARIOS_BI_TRG
BEFORE INSERT ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_USUARIOS_ID_USUARIO_PK := FIDE_USUARIOS_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    -- Validación de contraseña (mínimo 8 caracteres)
    IF LENGTH(:NEW.CONTRASENA) < 8 THEN
        RAISE_APPLICATION_ERROR(-20001, 'La contraseña debe tener al menos 8 caracteres');
    END IF;
END;
/

-- 11. Trigger para FIDE_PROVEEDORES_TB
CREATE OR REPLACE TRIGGER FIDE_PROVEEDORES_BI_TRG
BEFORE INSERT ON FIDE_PROVEEDORES_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_PROVEEDORES_ID_PROVEEDOR_PK := FIDE_PROVEEDORES_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/

-- 12. Trigger para FIDE_CATEGORIAS_TB
CREATE OR REPLACE TRIGGER FIDE_CATEGORIAS_BI_TRG
BEFORE INSERT ON FIDE_CATEGORIAS_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_CATEGORIAS_ID_CATEGORIA_PK := FIDE_CATEGORIAS_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/

-- 13. Trigger para FIDE_PRODUCTOS_TB
CREATE OR REPLACE TRIGGER FIDE_PRODUCTOS_BI_TRG
BEFORE INSERT ON FIDE_PRODUCTOS_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_PRODUCTOS_ID_PRODUCTO_PK := FIDE_PRODUCTOS_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    -- Validación de precio positivo
    IF :NEW.PRECIO_UNITARIO <= 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'El precio unitario debe ser mayor que cero');
    END IF;
END;
/

-- 14. Trigger para FIDE_INVENTARIOS_TB
CREATE OR REPLACE TRIGGER FIDE_INVENTARIOS_BI_TRG
BEFORE INSERT ON FIDE_INVENTARIOS_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_INVENTARIOS_ID_INVENTARIO_PK := FIDE_INVENTARIOS_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/

-- 15. Trigger para FIDE_DESCUENTOS_TB
CREATE OR REPLACE TRIGGER FIDE_DESCUENTOS_BI_TRG
BEFORE INSERT ON FIDE_DESCUENTOS_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_DESCUENTOS_ID_DESCUENTO_PK := FIDE_DESCUENTOS_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    -- Validación de fechas de descuento
    IF :NEW.FECHA_INICIO >= :NEW.FECHA_FIN THEN
        RAISE_APPLICATION_ERROR(-20003, 'La fecha de inicio debe ser anterior a la fecha de fin');
    END IF;
    -- Validación de porcentaje
    IF :NEW.PORCENTAJE <= 0 OR :NEW.PORCENTAJE > 100 THEN
        RAISE_APPLICATION_ERROR(-20004, 'El porcentaje debe estar entre 0 y 100');
    END IF;
END;
/

-- 16. Trigger para FIDE_PROMOCIONES_TB
CREATE OR REPLACE TRIGGER FIDE_PROMOCIONES_BI_TRG
BEFORE INSERT ON FIDE_PROMOCIONES_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_PROMOCIONES_ID_PROMOCION_PK := FIDE_PROMOCIONES_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    -- Validación de fechas de promoción
    IF :NEW.FECHA_INICIO >= :NEW.FECHA_FIN THEN
        RAISE_APPLICATION_ERROR(-20005, 'La fecha de inicio debe ser anterior a la fecha de fin');
    END IF;
END;
/

-- 17. Trigger para FIDE_COMPRAS_TB
CREATE OR REPLACE TRIGGER FIDE_COMPRAS_BI_TRG
BEFORE INSERT ON FIDE_COMPRAS_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_COMPRAS_ID_COMPRA_PK := FIDE_COMPRAS_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    -- Generamos números de orden automático
    IF :NEW.NUMERO_ORDEN IS NULL THEN
        :NEW.NUMERO_ORDEN := 'ORD-' || TO_CHAR(SYSDATE, 'YYYYMMDD') || '-' || LPAD(FIDE_COMPRAS_SEQ.CURRVAL, 6, '0');
    END IF;
END;
/

-- 18. Trigger para FIDE_DETALLES_COMPRA_TB
CREATE OR REPLACE TRIGGER FIDE_DETALLES_COMPRA_BI_TRG
BEFORE INSERT ON FIDE_DETALLES_COMPRA_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_DETALLES_COMPRA_ID_DETALLE_PK := FIDE_DETALLES_COMPRA_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    -- Aquí se calcula el subtotal automáticamente
    :NEW.SUBTOTAL := :NEW.CANTIDAD * :NEW.PRECIO_UNITARIO;
END;
/

-- 19. Trigger para FIDE_FACTURAS_TB
CREATE OR REPLACE TRIGGER FIDE_FACTURAS_BI_TRG
BEFORE INSERT ON FIDE_FACTURAS_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_FACTURAS_ID_FACTURA_PK := FIDE_FACTURAS_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    -- Generamos números de factura automáticos
    IF :NEW.NUMERO_FACTURA IS NULL THEN
        :NEW.NUMERO_FACTURA := 'FAC-' || TO_CHAR(SYSDATE, 'YYYYMMDD') || '-' || LPAD(FIDE_FACTURAS_SEQ.CURRVAL, 6, '0');
    END IF;
    -- Calcular total si subtotal está presente
    IF :NEW.SUBTOTAL IS NOT NULL THEN
        :NEW.TOTAL := :NEW.SUBTOTAL + NVL(:NEW.IMPUESTO, 0) - NVL(:NEW.DESCUENTO_TOTAL, 0);
    END IF;
END;
/

-- 20. Trigger para FIDE_DETALLES_FACTURA_TB
CREATE OR REPLACE TRIGGER FIDE_DETALLES_FACTURA_BI_TRG
BEFORE INSERT ON FIDE_DETALLES_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_DETALLES_FACTURA_ID_DETALLE_PK := FIDE_DETALLES_FACTURA_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    -- Calcular subtotal automáticamente
    :NEW.SUBTOTAL := :NEW.CANTIDAD * :NEW.PRECIO_UNITARIO - NVL(:NEW.DESCUENTO_APLICADO, 0);
END;
/

-- 21. Trigger para FIDE_CLIENTES_DESCUENTO_TB
CREATE OR REPLACE TRIGGER FIDE_CLIENTES_DESCUENTO_BI_TRG
BEFORE INSERT ON FIDE_CLIENTES_DESCUENTO_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_CLIENTES_DESCUENTO_ID_CLIENTE_DESCUENTO_PK := FIDE_CLIENTES_DESCUENTO_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/

-- 22. Trigger para FIDE_PLANILLAS_TB
CREATE OR REPLACE TRIGGER FIDE_PLANILLAS_BI_TRG
BEFORE INSERT ON FIDE_PLANILLAS_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_PLANILLAS_ID_PLANILLA_PK := FIDE_PLANILLAS_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    -- Validación de mes y año
    IF :NEW.MES < 1 OR :NEW.MES > 12 THEN
        RAISE_APPLICATION_ERROR(-20006, 'El mes debe estar entre 1 y 12');
    END IF;
    
    IF :NEW.ANIO < 2000 OR :NEW.ANIO > 2100 THEN
        RAISE_APPLICATION_ERROR(-20007, 'El año debe estar entre 2000 y 2100');
    END IF;
    -- Calcular salario neto si salario bruto y deducciones están presentes
    IF :NEW.SALARIO_BRUTO IS NOT NULL THEN
        :NEW.SALARIO_NETO := :NEW.SALARIO_BRUTO - NVL(:NEW.DEDUCCIONES, 0);
    END IF;
END;
/

-- 23. Trigger para FIDE_ASISTENCIA_TB
CREATE OR REPLACE TRIGGER FIDE_ASISTENCIA_BI_TRG
BEFORE INSERT ON FIDE_ASISTENCIA_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_ASISTENCIA_ID_ASISTENCIA_PK := FIDE_ASISTENCIA_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    -- Establecer hora de entrada si no está especificada
    IF :NEW.HORA_ENTRADA IS NULL THEN
        :NEW.HORA_ENTRADA := SYSTIMESTAMP;
    END IF;
END;
/

-- 24. Trigger para FIDE_DEVOLUCIONES_TB
CREATE OR REPLACE TRIGGER FIDE_DEVOLUCIONES_BI_TRG
BEFORE INSERT ON FIDE_DEVOLUCIONES_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_DEVOLUCIONES_ID_DEVOLUCION_PK := FIDE_DEVOLUCIONES_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
END;
/

-- 25. Trigger para FIDE_CONTRATOS_PROVEEDORES_TB
CREATE OR REPLACE TRIGGER FIDE_CONTRATOS_PROVEEDORES_BI_TRG
BEFORE INSERT ON FIDE_CONTRATOS_PROVEEDORES_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_CONTRATOS_PROVEEDORES_ID_CONTRATO_PK := FIDE_CONTRATOS_PROVEEDORES_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    -- Validación de fechas de contrato
    IF :NEW.FECHA_INICIO >= NVL(:NEW.FECHA_FIN, :NEW.FECHA_INICIO + 1) THEN
        RAISE_APPLICATION_ERROR(-20008, 'La fecha de inicio debe ser anterior a la fecha de fin');
    END IF;
END;
/

-- 26. Trigger para FIDE_PAGOS_PROVEEDORES_TB
CREATE OR REPLACE TRIGGER FIDE_PAGOS_PROVEEDORES_BI_TRG
BEFORE INSERT ON FIDE_PAGOS_PROVEEDORES_TB
FOR EACH ROW
BEGIN
    :NEW.FIDE_PAGOS_PROVEEDORES_ID_PAGO_PK := FIDE_PAGOS_PROVEEDORES_SEQ.NEXTVAL;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.ACCION := 'INSERT';
    -- Generar número de referencia si no está especificado
    IF :NEW.NUMERO_REFERENCIA IS NULL THEN
        :NEW.NUMERO_REFERENCIA := 'PAGO-' || TO_CHAR(SYSDATE, 'YYYYMMDD') || '-' || LPAD(FIDE_PAGOS_PROVEEDORES_SEQ.CURRVAL, 6, '0');
    END IF;
END;
/

--- Triggers de update para auditoría por tuplas.

-- 1. Trigger para FIDE_ESTADOS_TB
CREATE OR REPLACE TRIGGER FIDE_ESTADOS_BU_TRG
BEFORE UPDATE ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/

-- 2. Trigger para FIDE_PROVINCIAS_TB
CREATE OR REPLACE TRIGGER FIDE_PROVINCIAS_BU_TRG
BEFORE UPDATE ON FIDE_PROVINCIAS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/

-- 3. Trigger para FIDE_CANTONES_TB
CREATE OR REPLACE TRIGGER FIDE_CANTONES_BU_TRG
BEFORE UPDATE ON FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/

-- 4. Trigger para FIDE_DISTRITOS_TB
CREATE OR REPLACE TRIGGER FIDE_DISTRITOS_BU_TRG
BEFORE UPDATE ON FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/

-- 5. Trigger para FIDE_DIRECCIONES_TB
CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_BU_TRG
BEFORE UPDATE ON FIDE_DIRECCIONES_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/

-- 6. Trigger para FIDE_PUESTOS_TB
CREATE OR REPLACE TRIGGER FIDE_PUESTOS_BU_TRG
BEFORE UPDATE ON FIDE_PUESTOS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/

-- 7. Trigger para FIDE_SUCURSALES_TB
CREATE OR REPLACE TRIGGER FIDE_SUCURSALES_BU_TRG
BEFORE UPDATE ON FIDE_SUCURSALES_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/

-- 8. Trigger para FIDE_CORREOS_TB
CREATE OR REPLACE TRIGGER FIDE_CORREOS_BU_TRG
BEFORE UPDATE ON FIDE_CORREOS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/

-- 9. Trigger para FIDE_TELEFONOS_TB
CREATE OR REPLACE TRIGGER FIDE_TELEFONOS_BU_TRG
BEFORE UPDATE ON FIDE_TELEFONOS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/

-- 10. Trigger para FIDE_USUARIOS_TB
CREATE OR REPLACE TRIGGER FIDE_USUARIOS_BU_TRG
BEFORE UPDATE ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
    -- Actualizar último acceso cuando se actualiza el usuario
    :NEW.ULTIMO_ACCESO := SYSDATE;
END;
/

-- 11. Trigger para FIDE_PROVEEDORES_TB
CREATE OR REPLACE TRIGGER FIDE_PROVEEDORES_BU_TRG
BEFORE UPDATE ON FIDE_PROVEEDORES_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/

-- 12. Trigger para FIDE_CATEGORIAS_TB
CREATE OR REPLACE TRIGGER FIDE_CATEGORIAS_BU_TRG
BEFORE UPDATE ON FIDE_CATEGORIAS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/

-- 13. Trigger para FIDE_PRODUCTOS_TB
CREATE OR REPLACE TRIGGER FIDE_PRODUCTOS_BU_TRG
BEFORE UPDATE ON FIDE_PRODUCTOS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
    -- Validación de precio positivo
    IF :NEW.PRECIO_UNITARIO <= 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'El precio unitario debe ser mayor que cero');
    END IF;
END;
/

-- 14. Trigger para FIDE_INVENTARIOS_TB
CREATE OR REPLACE TRIGGER FIDE_INVENTARIOS_BU_TRG
BEFORE UPDATE ON FIDE_INVENTARIOS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
    -- Actualizar fecha de actualización
    :NEW.FECHA_ACTUALIZACION := SYSDATE;
END;
/

-- 15. Trigger para FIDE_DESCUENTOS_TB
CREATE OR REPLACE TRIGGER FIDE_DESCUENTOS_BU_TRG
BEFORE UPDATE ON FIDE_DESCUENTOS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/

-- 16. Trigger para FIDE_PROMOCIONES_TB
CREATE OR REPLACE TRIGGER FIDE_PROMOCIONES_BU_TRG
BEFORE UPDATE ON FIDE_PROMOCIONES_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/

-- 17. Trigger para FIDE_COMPRAS_TB
CREATE OR REPLACE TRIGGER FIDE_COMPRAS_BU_TRG
BEFORE UPDATE ON FIDE_COMPRAS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/

-- 18. Trigger para FIDE_DETALLES_COMPRA_TB
CREATE OR REPLACE TRIGGER FIDE_DETALLES_COMPRA_BU_TRG
BEFORE UPDATE ON FIDE_DETALLES_COMPRA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
    -- Recalcular subtotal si cambia cantidad o precio
    :NEW.SUBTOTAL := :NEW.CANTIDAD * :NEW.PRECIO_UNITARIO;
END;
/

-- 19. Trigger para FIDE_FACTURAS_TB
CREATE OR REPLACE TRIGGER FIDE_FACTURAS_BU_TRG
BEFORE UPDATE ON FIDE_FACTURAS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
    -- Recalcular total si cambia subtotal, impuesto o descuento
    IF :NEW.SUBTOTAL IS NOT NULL THEN
        :NEW.TOTAL := :NEW.SUBTOTAL + NVL(:NEW.IMPUESTO, 0) - NVL(:NEW.DESCUENTO_TOTAL, 0);
    END IF;
END;
/

-- 20. Trigger para FIDE_DETALLES_FACTURA_TB
CREATE OR REPLACE TRIGGER FIDE_DETALLES_FACTURA_BU_TRG
BEFORE UPDATE ON FIDE_DETALLES_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
    -- Recalcular subtotal si cambia cantidad, precio o descuento
    :NEW.SUBTOTAL := :NEW.CANTIDAD * :NEW.PRECIO_UNITARIO - NVL(:NEW.DESCUENTO_APLICADO, 0);
END;
/

-- 21. Trigger para FIDE_CLIENTES_DESCUENTO_TB
CREATE OR REPLACE TRIGGER FIDE_CLIENTES_DESCUENTO_BU_TRG
BEFORE UPDATE ON FIDE_CLIENTES_DESCUENTO_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/

-- 22. Trigger para FIDE_PLANILLAS_TB
CREATE OR REPLACE TRIGGER FIDE_PLANILLAS_BU_TRG
BEFORE UPDATE ON FIDE_PLANILLAS_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
    -- Recalcular salario neto si cambia salario bruto o deducciones
    IF :NEW.SALARIO_BRUTO IS NOT NULL THEN
        :NEW.SALARIO_NETO := :NEW.SALARIO_BRUTO - NVL(:NEW.DEDUCCIONES, 0);
    END IF;
END;
/

-- 23. Trigger para FIDE_ASISTENCIA_TB
CREATE OR REPLACE TRIGGER FIDE_ASISTENCIA_BU_TRG
BEFORE UPDATE ON FIDE_ASISTENCIA_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/

-- 24. Trigger para FIDE_DEVOLUCIONES_TB
CREATE OR REPLACE TRIGGER FIDE_DEVOLUCIONES_BU_TRG
BEFORE UPDATE ON FIDE_DEVOLUCIONES_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/

-- 25. Trigger para FIDE_CONTRATOS_PROVEEDORES_TB
CREATE OR REPLACE TRIGGER FIDE_CONTRATOS_PROVEEDORES_BU_TRG
BEFORE UPDATE ON FIDE_CONTRATOS_PROVEEDORES_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/

-- 26. Trigger para FIDE_PAGOS_PROVEEDORES_TB
CREATE OR REPLACE TRIGGER FIDE_PAGOS_PROVEEDORES_BU_TRG
BEFORE UPDATE ON FIDE_PAGOS_PROVEEDORES_TB
FOR EACH ROW
BEGIN
    :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
    :NEW.ACCION := 'UPDATE';
END;
/

--- Triggers adicionales según lo que necesitamos.

-- 1. Trigger para control de stock bajo
CREATE OR REPLACE TRIGGER FIDE_INVENTARIOS_STOCK_TRG
BEFORE INSERT OR UPDATE ON FIDE_INVENTARIOS_TB
FOR EACH ROW
DECLARE
    v_producto_nombre VARCHAR2(150);
    v_sucursal_nombre VARCHAR2(150);
BEGIN
    -- Verificar si el stock está por debajo del mínimo
    IF :NEW.CANTIDAD_STOCK < :NEW.CANTIDAD_MINIMA THEN
        -- Obtener nombre del producto y sucursal para el mensaje
        SELECT NOMBRE_PRODUCTO INTO v_producto_nombre 
        FROM FIDE_PRODUCTOS_TB 
        WHERE FIDE_PRODUCTOS_ID_PRODUCTO_PK = :NEW.FIDE_INVENTARIOS_ID_PRODUCTO_FK;
        SELECT NOMBRE_SUCURSAL INTO v_sucursal_nombre
        FROM FIDE_SUCURSALES_TB
        WHERE FIDE_SUCURSALES_ID_SUCURSAL_PK = :NEW.FIDE_INVENTARIOS_ID_SUCURSAL_FK;
        -- Registrar alerta (podría insertarse en una tabla de alertas)
        DBMS_OUTPUT.PUT_LINE('ALERTA: Stock bajo para producto ' || v_producto_nombre || 
                            ' en sucursal ' || v_sucursal_nombre || 
                            '. Stock actual: ' || :NEW.CANTIDAD_STOCK || 
                            ', Mínimo requerido: ' || :NEW.CANTIDAD_MINIMA);
    END IF;
END;
/

-- 2. Trigger para control de vencimientos de productos
CREATE OR REPLACE TRIGGER FIDE_PRODUCTOS_VENCIMIENTO_TRG
BEFORE INSERT OR UPDATE ON FIDE_PRODUCTOS_TB
FOR EACH ROW
BEGIN
    -- Verificar si la fecha de vencimiento está próxima
    IF :NEW.FECHA_VENCIMIENTO IS NOT NULL AND 
       :NEW.FECHA_VENCIMIENTO < SYSDATE + 30 THEN
        
        DBMS_OUTPUT.PUT_LINE('ALERTA: Producto ' || :NEW.NOMBRE_PRODUCTO || 
                            ' está próximo a vencer. Fecha: ' || TO_CHAR(:NEW.FECHA_VENCIMIENTO, 'DD/MM/YYYY'));
    END IF;
END;
/

-- 3. Trigger para acumulación de puntos de lealtad
CREATE OR REPLACE TRIGGER FIDE_FACTURAS_PUNTOS_TRG
AFTER INSERT ON FIDE_FACTURAS_TB
FOR EACH ROW
DECLARE
    v_puntos NUMBER;
BEGIN
    -- Calcular puntos (1 punto por cada 1000 colones de compra)
    v_puntos := TRUNC(:NEW.TOTAL / 1000);
    IF v_puntos > 0 THEN
        -- Actualizar puntos de lealtad del cliente
        UPDATE FIDE_USUARIOS_TB
        SET PUNTOS_LEALTAD = PUNTOS_LEALTAD + v_puntos
        WHERE FIDE_USUARIOS_ID_USUARIO_PK = :NEW.FIDE_FACTURAS_ID_CLIENTE_FK;
        
        DBMS_OUTPUT.PUT_LINE('Se han asignado ' || v_puntos || ' puntos de lealtad al cliente ID: ' || 
                            :NEW.FIDE_FACTURAS_ID_CLIENTE_FK);
    END IF;
END;
/

-- 4. Trigger para validar horarios de asistencia
CREATE OR REPLACE TRIGGER FIDE_ASISTENCIA_HORARIOS_TRG
BEFORE INSERT OR UPDATE ON FIDE_ASISTENCIA_TB
FOR EACH ROW
DECLARE
    v_hora_entrada_esperada TIMESTAMP;
    v_tolerancia_minutos NUMBER := 15; -- 15 minutos de tolerancia
BEGIN
    -- Establecer hora de entrada esperada (8:00 AM)
    v_hora_entrada_esperada := TRUNC(:NEW.FECHA_ASISTENCIA) + INTERVAL '8' HOUR;
    -- Verificar si llegó tarde
    IF :NEW.HORA_ENTRADA > v_hora_entrada_esperada + (v_tolerancia_minutos/1440) THEN
        DBMS_OUTPUT.PUT_LINE('REGISTRO: Empleado ID ' || :NEW.FIDE_ASISTENCIA_ID_EMPLEADO_FK || 
                            ' llegó tarde el ' || TO_CHAR(:NEW.FECHA_ASISTENCIA, 'DD/MM/YYYY'));
    END IF;
END;
/

-- 5. Trigger para actualizar inventario después de una venta
CREATE OR REPLACE TRIGGER FIDE_DETALLES_FACTURA_INVENTARIO_TRG
AFTER INSERT ON FIDE_DETALLES_FACTURA_TB
FOR EACH ROW
DECLARE
    v_sucursal_id NUMBER;
BEGIN
    -- Obtener la sucursal de la factura
    SELECT FIDE_FACTURAS_ID_SUCURSAL_FK INTO v_sucursal_id
    FROM FIDE_FACTURAS_TB
    WHERE FIDE_FACTURAS_ID_FACTURA_PK = :NEW.FIDE_DETALLES_FACTURA_ID_FACTURA_FK;
    -- Actualizar el inventario
    UPDATE FIDE_INVENTARIOS_TB
    SET CANTIDAD_STOCK = CANTIDAD_STOCK - :NEW.CANTIDAD,
        FECHA_ACTUALIZACION = SYSDATE
    WHERE FIDE_INVENTARIOS_ID_PRODUCTO_FK = :NEW.FIDE_DETALLES_FACTURA_ID_PRODUCTO_FK
      AND FIDE_INVENTARIOS_ID_SUCURSAL_FK = v_sucursal_id;
    
    DBMS_OUTPUT.PUT_LINE('Inventario actualizado: Producto ID ' || 
                        :NEW.FIDE_DETALLES_FACTURA_ID_PRODUCTO_FK || 
                        ' reducido en ' || :NEW.CANTIDAD || ' unidades');
END;
/

-- 6. Trigger para control de aprobación de compras
CREATE OR REPLACE TRIGGER FIDE_COMPRAS_APROBACION_TRG
BEFORE UPDATE ON FIDE_COMPRAS_TB
FOR EACH ROW
BEGIN
    -- Validar que solo administradores o gerentes puedan aprobar compras
    IF :NEW.ESTADO_COMPRA = 'APROBADA' AND :OLD.ESTADO_COMPRA != 'APROBADA' THEN
        DECLARE
            v_tipo_usuario VARCHAR2(50);
        BEGIN
            SELECT TIPO_USUARIO INTO v_tipo_usuario
            FROM FIDE_USUARIOS_TB
            WHERE FIDE_USUARIOS_ID_USUARIO_PK = :NEW.FIDE_COMPRAS_ID_EMPLEADO_FK;
            
            IF v_tipo_usuario NOT IN ('ADMIN', 'GERENTE') THEN
                RAISE_APPLICATION_ERROR(-20009, 'Solo administradores o gerentes pueden aprobar compras');
            END IF;
        END;
    END IF;
END;
/

-- 7. Trigger para validar promociones activas
CREATE OR REPLACE TRIGGER FIDE_PROMOCIONES_VIGENCIA_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROMOCIONES_TB
FOR EACH ROW
BEGIN
    -- Verificar que la promoción esté dentro del rango de fechas válido
    IF :NEW.FECHA_INICIO > SYSDATE THEN
        DBMS_OUTPUT.PUT_LINE('INFORMACIÓN: Promoción ' || :NEW.NOMBRE_PROMOCION || 
                            ' programada para iniciar el ' || TO_CHAR(:NEW.FECHA_INICIO, 'DD/MM/YYYY'));
    ELSIF :NEW.FECHA_FIN < SYSDATE THEN
        DBMS_OUTPUT.PUT_LINE('ADVERTENCIA: Promoción ' || :NEW.NOMBRE_PROMOCION || 
                            ' ha expirado el ' || TO_CHAR(:NEW.FECHA_FIN, 'DD/MM/YYYY'));
    END IF;
END;
/

-- 8. Trigger para validar contratos de proveedores
CREATE OR REPLACE TRIGGER FIDE_CONTRATOS_VIGENCIA_TRG
BEFORE INSERT OR UPDATE ON FIDE_CONTRATOS_PROVEEDORES_TB
FOR EACH ROW
BEGIN
    -- Verificar que el contrato no esté vencido
    IF :NEW.FECHA_FIN IS NOT NULL AND :NEW.FECHA_FIN < SYSDATE THEN
        DBMS_OUTPUT.PUT_LINE('CONTRATO VENCIDO: ' || :NEW.NUMERO_CONTRATO || 
                            ' con proveedor ID ' || :NEW.FIDE_CONTRATOS_PROVEEDORES_ID_PROVEEDOR_FK);
    END IF;
END;
/

-- 9. Trigger para cálculo automático de planillas
CREATE OR REPLACE TRIGGER FIDE_PLANILLAS_CALCULO_TRG
BEFORE INSERT ON FIDE_PLANILLAS_TB
FOR EACH ROW
DECLARE
    v_salario_base NUMBER(10,2);
    v_dias_trabajados NUMBER;
    v_deducciones_fijas NUMBER(10,2) := 0;
BEGIN
    -- Obtener salario base del puesto
    SELECT P.SALARIO_BASE INTO v_salario_base
    FROM FIDE_USUARIOS_TB U
    JOIN FIDE_PUESTOS_TB P ON U.FIDE_USUARIOS_ID_PUESTO_FK = P.FIDE_PUESTOS_ID_PUESTO_PK
    WHERE U.FIDE_USUARIOS_ID_USUARIO_PK = :NEW.FIDE_PLANILLAS_ID_EMPLEADO_FK;
    -- Calcular días trabajados
    v_dias_trabajados := 22;
    -- Calcular salario bruto
    :NEW.SALARIO_BRUTO := v_salario_base * (v_dias_trabajados / 30);
    -- Calcular deducciones (CCSS, renta, etc.)
    v_deducciones_fijas := :NEW.SALARIO_BRUTO * 0.10; -- 10%
    :NEW.DEDUCCIONES := v_deducciones_fijas;
    :NEW.SALARIO_NETO := :NEW.SALARIO_BRUTO - :NEW.DEDUCCIONES;
    DBMS_OUTPUT.PUT_LINE('Planilla calculada para empleado ID ' || 
                        :NEW.FIDE_PLANILLAS_ID_EMPLEADO_FK || 
                        ': Bruto=' || :NEW.SALARIO_BRUTO || 
                        ', Neto=' || :NEW.SALARIO_NETO);
END;
/
